-- Migration: inserir admin na tabela de usuarios
-- Data: 2026-08-20
-- Descrição: Criação do admin
--
-- A senha do admin NÃO fica mais neste arquivo (o hash antigo era o bcrypt
-- público de "password"). Para criar/atualizar o admin, defina ADMIN_EMAIL e
-- ADMIN_PASSWORD no .env e rode:
--
--     npm run seed:admin
--
-- (ver backend/scripts/seedAdmin.js)
